### ISSUE TITLE
When i make a mapping with suggesrted settings it errors out saying it found duplicate names and errors wirth StringUtils

### ISSUE THREAD

**Issue by stealthyzakki** [ItsMeFrenzy/Reaper#3]

**Comment by ItsMeFrenzy** [comment]
Resolved the StackOverflow issue, the reason it was happening was because there is a very limited amount of combinations lower name length values can actually generate. 

From now on, if it's a lower value, it'll just be set to 10 for now, you should be using about 10-15 for name length anyway.

Also added a debug boolean for toggling the duplicate names being printed.
